### ISSUE TITLE
Cant fetch collection data on a new channel

### ISSUE THREAD

**Issue by rohanrajpal** [vendure-ecommerce/vendure#599]
**Describe the bug**

On fetching the products i a collection, I get the following error
![image](https://user-images.githubusercontent.com/7023147/102783552-19785e00-43c1-11eb-98d9-85dd3696124e.png)
Vendure logs
```bash
[run:worker] error 12/21/20, 1:37 PM - [RpcExceptionsHandler] error.no-price-found-for-channel[run:worker] Error: error.no-price-found-for-channel
[run:worker]     at ProductVariantService.applyChannelPriceAndTax (/home/rohan/vendure-dev/packages/core/src/service/services/product-variant.service.ts:398:19)
[run:worker]     at /home/rohan/vendure-dev/packages/core/src/plugin/default-search-plugin/indexer/indexer.controller.ts:318:50
[run:worker]     at Array.map (<anonymous>)[run:worker]     at IndexerController.hydrateVariants (/home/rohan/vendure-dev/packages/core/src/plugin/default-search-plugin/indexer/indexer.controller.ts:318:14)[run:worker]     at /home/rohan/vendure-dev/packages/core/src/plugin/default-search-plugin/indexer/indexer.controller.ts:123:43
[run:worker]     at processTicksAndRejections (internal/process/task_queues.js:97:5)
[run:worker]     at /home/rohan/vendure-dev/packages/core/src/worker/async-observable.ts:30:32
[run:server] error 12/21/20, 1:37 PM - [Vendure Server] {"status":"error","message":"Internal server error"}
```

**To Reproduce**

1. Create a new channel
2. Add some products with facetvalues
3. Create a new collection and filter it by a particular facet value
4. Try to retrieve the content of the collection

**Expected behavior**
I expect to get the contents of the channel

**Environment (please complete the following information):**
 - @vendure/core version: Vendure dev (next branch)
 - Nodejs version: 12.20
 - Database (mysql/postgres etc): Postgres

**Additional context**
Slack chat 
https://vendure-ecommerce.slack.com/archives/CKYMF0ZTJ/p1608543291113100

**Comment by rohanrajpal** [comment]
Some more context

So I'm building my own dashboard. Normally i didnt get this error with Vendure. But if using the `admin-api` I create a collection and try to fetch the products. Vendure starts throwing this error and then even with the admin api I start getting the above problem

The queries i'm using to create a collection are exactly same as in the admin ui. I just tapped all graphql requests and replicated them in my own dashboard. However, I dont do the `getalljobs` and `healthcheck` requests, which I see happening after every request in the admin ui.

**Comment by michaelbromley** [comment]
Do the graphql mutations mentioned:

```
Add some products with facetvalues
Create a new collection and filter it by a particular facet value
Try to retrieve the content of the collection
```

happen in rapid succession? Or one after the other as in manual input? Just wondering if there might be a race condition at play.

**Comment by michaelbromley** [comment]
I think I just fixed this in v0.18.1. Can you verify once you get a chance to update?

**Comment by rohanrajpal** [comment]
> I think I just fixed this in v0.18.1. Can you verify once you get a chance to update?

Hey Michael, just updated Vendure and the issue persists. 
![image](https://user-images.githubusercontent.com/7023147/104043892-803fa900-5202-11eb-9792-1574169e64d9.png)

```
[run:server] error 1/8/21, 5:09 PM - [Vendure Server] update or delete on table "channel" violates foreign key constraint "FK_eb87ef1e234444728138302263b" on table "session"
[run:server] QueryFailedError: update or delete on table "channel" violates foreign key constraint "FK_eb87ef1e234444728138302263b" on table "session"
[run:server]     at new QueryFailedError (/home/rohan/vendure/src/error/QueryFailedError.ts:9:9)
[run:server]     at Query.callback (/home/rohan/vendure/src/driver/postgres/PostgresQueryRunner.ts:195:30)
[run:server]     at Query.handleError (/home/rohan/vendure/node_modules/pg/lib/query.js:128:19)
[run:server]     at Client._handleErrorMessage (/home/rohan/vendure/node_modules/pg/lib/client.js:335:17)
[run:server]     at Connection.emit (events.js:314:20)
[run:server]     at Connection.EventEmitter.emit (domain.js:483:12)
[run:server]     at /home/rohan/vendure/node_modules/pg/lib/connection.js:115:12
[run:server]     at Parser.parse (/home/rohan/vendure/node_modules/pg-protocol/src/parser.ts:102:9)
[run:server]     at Socket.<anonymous> (/home/rohan/vendure/node_modules/pg-protocol/src/index.ts:7:48)
[run:server]     at Socket.emit (events.js:314:20)
```

**Comment by michaelbromley** [comment]
You'll need to follow the migration guide to upgrade: https://www.vendure.io/blog/2020/12/announcing-vendure-v0.18.0/#breaking-changes--migration-guide

**Comment by rohanrajpal** [comment]
> You'll need to follow the migration guide to upgrade: https://www.vendure.io/blog/2020/12/announcing-vendure-v0.18.0/#breaking-changes--migration-guide

My bad, I thought this issue was the channel deletion issue. Let me try this out.
Also, I updated from 0.18.0 to 0.18.1, so think I need not follow the migration guide?

**Comment by rohanrajpal** [comment]
Just tried it out. It seems to be working now, thanks a lot for fixing this!
